### ISSUE TITLE
Issue saving model using logging package

### ISSUE THREAD

**Issue by SteveH-US** [sindbach/doc2vec_pymongo#1]
When running 
```
python ./modeller.py --db topics --coll movies --model example.model
```

I see this error
```
INFO : EPOCH - 10 : training on 105501 raw words (98608 effective words) took 0.2s, 516351 effective words/s
INFO : training on a 1055010 raw words (985881 effective words) took 2.0s, 504122 effective words/s
INFO : saving Doc2Vec object under example.model, separately None
INFO : saved example.model
INFO : precomputing L2-norms of doc weight vectors
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```
Repeated many times.

**Comment by sindbach** [comment]
Hi @SteveH-US, 

Sorry for the late reply. This has been fixed in `main`.
Please give this another try when you have the chance. 

Thanks
